In [7]:
import pandas as pd

In [7]:
import sys
print(sys.executable)

C:\ProgramData\Anaconda3\python.exe

In [11]:
! C:\\ProgramData\\Anaconda3\\python.exe -m pip install keras

Collecting keras
  Using cached keras-3.8.0-py3-none-any.whl (1.3 MB)
Collecting namex
  Using cached namex-0.0.8-py3-none-any.whl (5.8 kB)
Collecting absl-py
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from keras) (1.20.3)
Collecting ml-dtypes
  Downloading ml_dtypes-0.5.1-cp39-cp39-win_amd64.whl (209 kB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from keras) (23.2)

WARNING: Ignoring invalid distribution -ygments (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ygments (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ygments (c:\programdata\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -ygments (c:\programdata\anaconda3\lib\site-packages)

Collecting optree
  Downloading optree-0.14.0-cp39-cp39-win_amd64.whl (286 kB)
Requirement already satisfied: h5py in c:\programdata\anaconda3\lib\site-packages (from keras) (3.2.1)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras) (13.7.1)
Collecting numpy
  Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl (15.9 MB)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\programdata\anaconda3\lib\site-packages (from optree->keras) (4.10.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras) (2.15.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Installing collected packages: numpy, optree, namex, ml-dtypes, absl-py, keras
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy-1.20.3.dist-info\\direct_url.json'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -ygments (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ygments (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ygments (c:\programdata\anaconda3\lib\site-packages)

In [4]:
!pip install keras

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: keras in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (3.8.0)
Requirement already satisfied: absl-py in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (2.1.0)
Requirement already satisfied: numpy in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (2.0.2)
Requirement already satisfied: rich in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (13.9.4)
Requirement already satisfied: namex in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (0.0.8)
Requirement already satisfied: h5py in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (3.12.1)
Requirement already satisfied: optree in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (0.14.0)
Requirement already satisfied: ml-dtypes in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (0.4.1)
Requirement already satisfied: packaging in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from keras) (24.2)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from optree->keras) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from rich->keras) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import keras as kf

ModuleNotFoundError: No module named 'keras'

In [2]:
!pip install geopy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopy in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\tramjeet\appdata\roaming\python\python312\site-packages (from geopy) (2.0)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
from datetime import datetime, timedelta

In [37]:
# handy function from the article
def haversine_vectorise(longitude_x, latitude_x, longitude_y, latitude_y):
    """Returns distance, in kilometers, between one set of longitude/latitude coordinates and another"""
    longitude_x, latitude_x, longitude_y, latitude_y = map(np.radians, [longitude_x, latitude_x, longitude_y, latitude_y])
 
    newlon = longitude_x - longitude_y
    newlat = latitude_x - latitude_y
 
    haver_formula = np.sin(newlat/2.0)**2 + np.cos(latitude_x) * np.cos(latitude_y) * np.sin(newlon/2.0)**2
 
    dist = 2 * np.arcsin(np.sqrt(haver_formula ))
    km = 3958 * dist #6367 for distance in KM for miles use 3958
    return km

In [5]:
import os
path = "C:\\Users\\tramjeet\\OneDrive - KPMG\\Documents\\_development\\git\\kgraph\\notebooks\\data\\"

In [11]:
df = pd.read_json(path+'tesco.json')

In [13]:
# df

### Use first row as column headers

In [14]:
df_norm = pd.json_normalize(df['data'])

In [15]:
df_norm

,id,sname,postcode,longitude,latitude,tel,address
0,13312,Tesco Metro Banff,0,-2.5198710,57.6648509,0,Carmelite St - AB45 Banff
1,13568,Tesco Superstore Dorchester,0,-2.4439952,50.7016867,0,Weymouth Ave - DT1 Dorchester
2,13824,Tesco Superstore King's Lynn,0,0.4176230,52.7577740,0,St Faith's Dr - PE30 King's Lynn
3,13313,Tesco Superstore Barrhead,0,-4.4004660,55.7977660,0,Kelburn St - G78 Barrhead
4,13825,Tesco Express London,0,-0.2416818,51.4932370,0,327-343 King St - W6 London
...,...,...,...,...,...,...,...
2322,14591,Tesco Rothwell,0,-1.4665086,53.7553758,0,128 Leeds Road - LS26 Rothwell
2323,14847,Tesco Leeds,0,-1.5316066,53.7897859,0,2 The Boulevard - LS10 Leeds
2324,15103,Tesco London,0,0.0260418,51.5785546,0,65-67 High Street - E11 London
2325,15359,Tesco London,0,-0.0610671,51.5485111,0,230 Dalston Lane - E8 London
2326,15615,Tesco Bedford,0,-0.4312297,52.1120801,0,13 Beauvais Square - MK42 Bedford

### Remove blank rows

In [17]:
df_clean = df_norm.drop(['postcode', 'tel'], axis=1)

In [18]:
df_clean

,id,sname,longitude,latitude,address
0,13312,Tesco Metro Banff,-2.5198710,57.6648509,Carmelite St - AB45 Banff
1,13568,Tesco Superstore Dorchester,-2.4439952,50.7016867,Weymouth Ave - DT1 Dorchester
2,13824,Tesco Superstore King's Lynn,0.4176230,52.7577740,St Faith's Dr - PE30 King's Lynn
3,13313,Tesco Superstore Barrhead,-4.4004660,55.7977660,Kelburn St - G78 Barrhead
4,13825,Tesco Express London,-0.2416818,51.4932370,327-343 King St - W6 London
...,...,...,...,...,...
2322,14591,Tesco Rothwell,-1.4665086,53.7553758,128 Leeds Road - LS26 Rothwell
2323,14847,Tesco Leeds,-1.5316066,53.7897859,2 The Boulevard - LS10 Leeds
2324,15103,Tesco London,0.0260418,51.5785546,65-67 High Street - E11 London
2325,15359,Tesco London,-0.0610671,51.5485111,230 Dalston Lane - E8 London
2326,15615,Tesco Bedford,-0.4312297,52.1120801,13 Beauvais Square - MK42 Bedford

### Prepare for cross join - remove columns not needed

In [19]:
df_join = df_clean.drop(['sname','address'], axis=1)

In [20]:
prod = pd.merge(df_join, df_join, how='cross')

In [21]:
prod

          id_x longitude_x  latitude_x   id_y longitude_y  latitude_y
0        13312  -2.5198710  57.6648509  13312  -2.5198710  57.6648509
1        13312  -2.5198710  57.6648509  13568  -2.4439952  50.7016867
2        13312  -2.5198710  57.6648509  13824   0.4176230  52.7577740
3        13312  -2.5198710  57.6648509  13313  -4.4004660  55.7977660
4        13312  -2.5198710  57.6648509  13825  -0.2416818  51.4932370
...        ...         ...         ...    ...         ...         ...
5414924  15615  -0.4312297  52.1120801  14591  -1.4665086  53.7553758
5414925  15615  -0.4312297  52.1120801  14847  -1.5316066  53.7897859
5414926  15615  -0.4312297  52.1120801  15103   0.0260418  51.5785546
5414927  15615  -0.4312297  52.1120801  15359  -0.0610671  51.5485111
5414928  15615  -0.4312297  52.1120801  15615  -0.4312297  52.1120801

[5414929 rows x 6 columns]

### Remove duplicate rows - code not working

In [24]:
result =prod.drop_duplicates(subset=['id_x', 'id_y'],keep='first')

In [39]:
result

,id_x,longitude_x,latitude_x,id_y,longitude_y,latitude_y,haversine_dist
0,13312,-2.519871,57.664851,13312,-2.519871,57.664851,0.000000
1,13312,-2.519871,57.664851,13568,-2.443995,50.701687,481.025999
2,13312,-2.519871,57.664851,13824,0.417623,52.757774,358.122629
3,13312,-2.519871,57.664851,13313,-4.400466,55.797766,147.344054
4,13312,-2.519871,57.664851,13825,-0.241682,51.493237,435.919200
...,...,...,...,...,...,...,...
5414924,15615,-0.431230,52.112080,14591,-1.466509,53.755376,121.424439
5414925,15615,-0.431230,52.112080,14847,-1.531607,53.789786,124.613132
5414926,15615,-0.431230,52.112080,15103,0.026042,51.578555,41.703461
5414927,15615,-0.431230,52.112080,15359,-0.061067,51.548511,42.016259
5414928,15615,-0.431230,52.112080,15615,-0.431230,52.112080,0.000000

### Change data types

In [ ]:
result["longitude_x"] = result.longitude_x.astype(float)
result["longitude_y"] = result.longitude_y.astype(float)
result["latitude_x"] = result.latitude_x.astype(float)
result["latitude_y"] = result.latitude_y.astype(float)

In [40]:
# result.dtypes

### Calculate distance (miles)

In [38]:
result['haversine_dist'] = haversine_vectorise(result.longitude_x, result.latitude_x, 
                                                     result.longitude_y, result.latitude_y)